// react-app/src/App.jsx
import { useState } from 'react';
import { keycloak } from './keycloak';
import { PublicPage } from './PublicPage';
import { SecuredPage } from './SecuredPage';

const API_BASE = import.meta.env.VITE_API_URL || '';

function App() {
  const [view, setView] = useState('public');
  const isLoggedIn = keycloak.authenticated;

  return (
    <div style={{ padding: '1.5rem', maxWidth: 800, margin: '0 auto' }}>
      <header style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
        <h1 style={{ margin: 0 }}>React + Keycloak</h1>
        <nav style={{ display: 'flex', gap: '0.5rem' }}>
          <button className={view === 'public' ? 'primary' : ''} onClick={() => setView('public')}>
            Public
          </button>
          <button className={view === 'secured' ? 'primary' : ''} onClick={() => setView('secured')}>
            Secured
          </button>
        </nav>
        <span style={{ marginLeft: 'auto' }}>
          {isLoggedIn ? (
            <>
              <span style={{ marginRight: '0.5rem' }}>{keycloak.tokenParsed?.preferred_username ?? 'User'}</span>
              <button onClick={() => keycloak.logout()}>Logout</button>
            </>
          ) : (
            <button className="primary" onClick={() => keycloak.login()}>
              Login
            </button>
          )}
        </span>
      </header>

      {view === 'public' && <PublicPage />}
      {view === 'secured' && <SecuredPage />}
    </div>
  );
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';
import Keycloak from 'keycloak-js';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <div class="layout">
      <header>
        <h1>Angular + Keycloak</h1>
        <nav>
          <a routerLink="/public" routerLinkActive="active">Public</a>
          <a routerLink="/secured" routerLinkActive="active">Secured</a>
        </nav>
        <span class="auth">
          @if (isLoggedIn()) {
            <span>{{ username() }}</span>
            <button (click)="logout()">Logout</button>
          } @else {
            <button class="primary" (click)="login()">Login</button>
          }
        </span>
      </header>
      <main>
        <router-outlet />
      </main>
    </div>
  `,
  styles: [`
    .layout { padding: 1.5rem; max-width: 800px; margin: 0 auto; }
    header { display: flex; gap: 1rem; align-items: center; margin-bottom: 1.5rem; flex-wrap: wrap; }
    h1 { margin: 0; }
    nav { display: flex; gap: 0.5rem; }
    nav a { color: #38bdf8; text-decoration: none; padding: 0.25rem 0.5rem; border-radius: 4px; }
    nav a.active { background: #1e293b; }
    .auth { margin-left: auto; display: flex; align-items: center; gap: 0.5rem; }
  `],
})
export class AppComponent {
  constructor(private keycloak: Keycloak) {}

  isLoggedIn(): boolean {
    return this.keycloak.authenticated === true;
  }

  username(): string {
    const parsed = this.keycloak.tokenParsed as { preferred_username?: string } | undefined;
    return parsed?.preferred_username ?? 'User';
  }

  login(): void {
    this.keycloak.login();
  }

  logout(): void {
    this.keycloak.logout();
  }
}
